version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "staging-todo-list-aws"
s3_bucket = "staging-todo-list-aws-pablo"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
